### ISSUE TITLE
Deployment Error: TASK [download : prep_kubeadm_images | Copy kubeadm binary from download dir to system path

### ISSUE THREAD

**Issue by amithanoop** [sguyennet/terraform-vsphere-kubespray#27]
Error:
TASK [download : prep_kubeadm_images | Copy kubeadm binary from download dir to system path] ***
Thursday 02 January 2020  22:01:04 +0530 (0:00:00.778)       0:09:40.886 ******
fatal: [k8s-kubespray-master-0 -> 10.12.43.220]: FAILED! => {"changed": false, "cmd": "sshpass", "msg": "[Errno 2] No such file or directory: b'sshpass': b'sshpass'", "rc": 2}

Details: 
Template Using : Ubuntu 18.04
For SSH login using user name and password

**Comment by gelmistefano** [comment]
Hi,
i've seen this issue in my tests. I've resolved changing "synchronize" with "copy":

```
  copy:
    src: "{{ local_release_dir }}/kubeadm-{{ kubeadm_version }}-{{ image_arch }}"
    dest: "{{ bin_dir }}/kubeadm"
    remote_src: yes
    mode: preserve
```

this issue is present in all "Copy ... binary from download dir"
